"""empty message

Revision ID: 099494930b61
Revises: 8eb7ba46bdce
Create Date: 2022-02-24 08:23:47.429787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '099494930b61'
down_revision = '8eb7ba46bdce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_program_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('program_type_id', 'collection_program_type', ['program_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_program_info', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('program_type_id')

    # ### end Alembic commands ###
