"""empty message

Revision ID: 0e5c96408724
Revises: 301cb14b69be
Create Date: 2024-10-16 10:50:12.736655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e5c96408724'
down_revision = '301cb14b69be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('general_program_popup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_entry_date', sa.String(length=32), nullable=True),
    sa.Column('row_update_date', sa.String(length=32), nullable=True),
    sa.Column('header_title', sa.String(length=32), nullable=True),
    sa.Column('icon', sa.String(length=32), nullable=True),
    sa.Column('site_field', sa.String(length=32), nullable=True),
    sa.Column('site_id', sa.String(length=32), nullable=True),
    sa.Column('link_field', sa.String(length=64), nullable=True),
    sa.Column('site_url', sa.String(length=2048), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sample_site_id', sa.Integer(), nullable=True),
    sa.Column('project_site_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_site_id'], ['project_area.id'], ),
    sa.ForeignKeyConstraint(['sample_site_id'], ['sample__site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('general_program_popup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_general_program_popup_sample_site_id'), ['sample_site_id'], unique=False)

    with op.batch_alter_table('beach_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_beach_access_access_name'), ['access_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_beach_access_sample_site_id'), ['sample_site_id'], unique=False)

    with op.batch_alter_table('boundary', schema=None) as batch_op:
        batch_op.create_unique_constraint('boundary_name', ['boundary_name'])

    with op.batch_alter_table('data_timeouts', schema=None) as batch_op:
        batch_op.create_foreign_key('site_type_id', 'site_type', ['site_type_id'], ['id'])
        batch_op.create_foreign_key('project_site_id', 'project_area', ['project_site_id'], ['id'])

    with op.batch_alter_table('site_message', schema=None) as batch_op:
        batch_op.create_unique_constraint('site_id', ['site_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('data_timeouts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('boundary', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('beach_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_beach_access_sample_site_id'))
        batch_op.drop_index(batch_op.f('ix_beach_access_access_name'))

    with op.batch_alter_table('general_program_popup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_general_program_popup_sample_site_id'))

    op.drop_table('general_program_popup')
    # ### end Alembic commands ###
