"""empty message

Revision ID: 0f2b93db7efc
Revises: c6c34c28580f
Create Date: 2022-04-11 10:31:17.435019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f2b93db7efc'
down_revision = 'c6c34c28580f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beach_ambassador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_entry_date', sa.String(length=32), nullable=True),
    sa.Column('row_update_date', sa.String(length=32), nullable=True),
    sa.Column('bcrs_id', sa.String(length=8), nullable=True),
    sa.Column('sample_site_id', sa.Integer(), nullable=True),
    sa.Column('site_surl', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['sample_site_id'], ['sample__site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beach_ambassador')
    # ### end Alembic commands ###
