"""empty message

Revision ID: 301cb14b69be
Revises: e76ab880d73c
Create Date: 2024-04-04 12:09:59.770608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '301cb14b69be'
down_revision = 'e76ab880d73c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_timeouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_entry_date', sa.String(length=32), nullable=True),
    sa.Column('row_update_date', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('hours_valid', sa.Integer(), nullable=True),
    sa.Column('site_type_id', sa.Integer(), nullable=True),
    sa.Column('project_site_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_site_id'], ['project_area.id'], ),
    sa.ForeignKeyConstraint(['site_type_id'], ['site_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_timeouts')
    # ### end Alembic commands ###
