"""empty message

Revision ID: 3bb7beb9c06c
Revises: d1fd9a9b9e05
Create Date: 2022-02-22 11:27:19.786357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb7beb9c06c'
down_revision = 'd1fd9a9b9e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_boundary__mapper')
    with op.batch_alter_table('boundary__mapper', schema=None) as batch_op:
        batch_op.alter_column('sample_site_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('boundary_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('project_info_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=128), nullable=True))
        batch_op.drop_column('sampling_program')
        batch_op.drop_column('swim_advisory_info')

    with op.batch_alter_table('sample__site', schema=None) as batch_op:
        batch_op.alter_column('temporary_site',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample__site', schema=None) as batch_op:
        batch_op.alter_column('temporary_site',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('project_info_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('swim_advisory_info', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('sampling_program', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('state')
        batch_op.drop_column('program')

    with op.batch_alter_table('boundary__mapper', schema=None) as batch_op:
        batch_op.alter_column('boundary_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sample_site_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_boundary__mapper',
    sa.Column('sample_site_id', sa.INTEGER(), nullable=False),
    sa.Column('boundary_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['boundary_id'], ['boundary.id'], ),
    sa.ForeignKeyConstraint(['sample_site_id'], ['sample__site.id'], )
    )
    # ### end Alembic commands ###
