"""empty message

Revision ID: 5a048aa260a7
Revises: 91cda64fb101
Create Date: 2022-02-23 15:27:22.631502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a048aa260a7'
down_revision = '91cda64fb101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    '''
    op.create_table('collection_program_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_entry_date', sa.String(length=32), nullable=True),
    sa.Column('row_update_date', sa.String(length=32), nullable=True),
    sa.Column('program_type', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    '''
    with op.batch_alter_table('collection_program_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collection_program_type', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_collection_program_type', 'collection_program_type', ['collection_program_type'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_program_info', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('collection_program_type')

    op.drop_table('collection_program_type')
    # ### end Alembic commands ###
