"""empty message

Revision ID: 8eb7ba46bdce
Revises: 61c615d1fbf4
Create Date: 2022-02-24 08:19:35.318308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eb7ba46bdce'
down_revision = '61c615d1fbf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_program_info', schema=None) as batch_op:
        batch_op.drop_constraint('fk_program_type_id', type_='foreignkey')
        batch_op.drop_column('program_type_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_program_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_type_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_program_type_id', 'collection_program_type', ['program_type_id'], ['id'])

    # ### end Alembic commands ###
