"""empty message

Revision ID: b7e6bdcebcd8
Revises: c0efd5d23ce2
Create Date: 2024-03-29 10:20:33.816023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e6bdcebcd8'
down_revision = 'c0efd5d23ce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beach_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_entry_date', sa.String(length=32), nullable=True),
    sa.Column('row_update_date', sa.String(length=32), nullable=True),
    sa.Column('county', sa.String(length=32), nullable=True),
    sa.Column('parking_spaces', sa.Integer(), nullable=True),
    sa.Column('parking_type', sa.String(length=32), nullable=True),
    sa.Column('parking_fee', sa.String(length=32), nullable=True),
    sa.Column('ada_parking', sa.String(length=8), nullable=True),
    sa.Column('ada_accessible', sa.String(length=8), nullable=True),
    sa.Column('rv_parking', sa.String(length=8), nullable=True),
    sa.Column('rv_spaces', sa.String(length=8), nullable=True),
    sa.Column('restrooms', sa.String(length=8), nullable=True),
    sa.Column('trash_cans', sa.String(length=8), nullable=True),
    sa.Column('recycling', sa.String(length=8), nullable=True),
    sa.Column('public_transportation', sa.String(length=8), nullable=True),
    sa.Column('type_of_access_path', sa.String(length=32), nullable=True),
    sa.Column('pet_regulations', sa.String(length=32), nullable=True),
    sa.Column('lifeguard', sa.String(length=8), nullable=True),
    sa.Column('access_sign', sa.String(length=8), nullable=True),
    sa.Column('consessions', sa.String(length=8), nullable=True),
    sa.Column('adopt_a_beach', sa.String(length=8), nullable=True),
    sa.Column('parking', sa.String(length=8), nullable=True),
    sa.Column('beach_name', sa.String(length=32), nullable=True),
    sa.Column('access_name', sa.String(length=32), nullable=True),
    sa.Column('location_address', sa.String(length=64), nullable=True),
    sa.Column('area', sa.String(length=32), nullable=True),
    sa.Column('adminstrative_body', sa.String(length=32), nullable=True),
    sa.Column('general_url', sa.String(length=2048), nullable=True),
    sa.Column('regulations_url', sa.String(length=2048), nullable=True),
    sa.Column('web_cam_url', sa.String(length=2048), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beach_access')
    # ### end Alembic commands ###
