"""empty message

Revision ID: c0efd5d23ce2
Revises: c9bd56388f14
Create Date: 2023-10-09 10:16:00.885009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0efd5d23ce2'
down_revision = 'c9bd56388f14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shell_cast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wkt_extent', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shell_cast', schema=None) as batch_op:
        batch_op.drop_column('wkt_extent')

    # ### end Alembic commands ###
