"""empty message

Revision ID: c6c34c28580f
Revises: 099494930b61
Create Date: 2022-03-23 08:19:30.726177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6c34c28580f'
down_revision = '099494930b61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample__site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('post_code', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('state_abbreviation', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample__site', schema=None) as batch_op:
        batch_op.drop_column('state_abbreviation')
        batch_op.drop_column('post_code')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
