"""empty message

Revision ID: cc1d0cef8ecb
Revises: c7fd7f06feb0
Create Date: 2022-02-23 13:17:33.186491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1d0cef8ecb'
down_revision = 'c7fd7f06feb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_program_info')
    op.drop_table('collection__program__info__mapper')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection__program__info__mapper',
    sa.Column('collection_program_info_id', sa.INTEGER(), nullable=False),
    sa.Column('project_area_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['collection_program_info_id'], ['collection_program_info.id'], ),
    sa.ForeignKeyConstraint(['project_area_id'], ['project_area.id'], ),
    sa.PrimaryKeyConstraint('collection_program_info_id', 'project_area_id')
    )
    op.create_table('collection_program_info',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('program', sa.TEXT(), nullable=True),
    sa.Column('state', sa.VARCHAR(length=128), nullable=True),
    sa.Column('row_entry_date', sa.VARCHAR(length=32), nullable=True),
    sa.Column('row_update_date', sa.VARCHAR(length=32), nullable=True),
    sa.Column('site_id', sa.INTEGER(), nullable=True),
    sa.Column('url', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('state_abbreviation', sa.VARCHAR(length=2), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['project_area.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
