"""empty message

Revision ID: ce39615f54c6
Revises: e7d52be7ab80
Create Date: 2024-03-29 10:56:14.230176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce39615f54c6'
down_revision = 'e7d52be7ab80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beach_access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sample_site_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('sample_site', 'sample__site', ['sample_site_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beach_access', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sample_site_id')

    # ### end Alembic commands ###
