"""empty message

Revision ID: de177b246d27
Revises: 301cb14b69be
Create Date: 2024-10-16 08:33:58.372265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de177b246d27'
down_revision = '301cb14b69be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_program_popup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_entry_date', sa.String(length=32), nullable=True),
    sa.Column('row_update_date', sa.String(length=32), nullable=True),
    sa.Column('header_title', sa.String(length=32), nullable=True),
    sa.Column('icon', sa.String(length=32), nullable=True),
    sa.Column('site_field', sa.String(length=32), nullable=True),
    sa.Column('site_name', sa.String(length=32), nullable=True),
    sa.Column('link_field', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sample_site_id', sa.Integer(), nullable=True),
    sa.Column('project_site_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_site_id'], ['project_area.id'], ),
    sa.ForeignKeyConstraint(['sample_site_id'], ['sample__site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('general_program_popup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_general_program_popup_sample_site_id'), ['sample_site_id'], unique=False)

    op.drop_table('beach_access-nokeys')
    op.drop_table('advisory_limits-nokeys')
    op.drop_table('shell_cast-nokeys')
    op.drop_table('data_timeouts-nokeys')
    op.drop_table('site_type-oldprod')
    op.drop_table('site_type-nokeys')
    op.drop_table('project_area-oldprod')
    op.drop_table('sample__site-nokeys')
    op.drop_table('project_area-nokeys')
    with op.batch_alter_table('advisory_limits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'project_area', ['site_id'], ['id'])

    with op.batch_alter_table('beach_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_beach_access_access_name'), ['access_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_beach_access_sample_site_id'), ['sample_site_id'], unique=False)

    with op.batch_alter_table('boundary', schema=None) as batch_op:
        batch_op.drop_constraint('project_site_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'project_area', ['project_site_id'], ['id'])

    with op.batch_alter_table('collection__program__info__mapper', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'project_area', ['project_area_id'], ['id'])

    with op.batch_alter_table('data_timeouts', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'project_area', ['project_site_id'], ['id'])
        batch_op.create_foreign_key(None, 'site_type', ['site_type_id'], ['id'])

    with op.batch_alter_table('sample__site', schema=None) as batch_op:
        batch_op.drop_constraint('site_type_id', type_='foreignkey')
        batch_op.drop_constraint('project_site_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'project_area', ['project_site_id'], ['id'])
        batch_op.create_foreign_key(None, 'site_type', ['site_type_id'], ['id'])

    with op.batch_alter_table('site_message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'project_area', ['site_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'project_area-oldprod', ['site_id'], ['id'])

    with op.batch_alter_table('sample__site', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('project_site_id', 'project_area-oldprod', ['project_site_id'], ['id'])
        batch_op.create_foreign_key('site_type_id', 'site_type-oldprod', ['site_type_id'], ['id'])

    with op.batch_alter_table('data_timeouts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('collection__program__info__mapper', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'project_area-oldprod', ['project_area_id'], ['id'])

    with op.batch_alter_table('boundary', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('project_site_id', 'project_area-oldprod', ['project_site_id'], ['id'])

    with op.batch_alter_table('beach_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_beach_access_sample_site_id'))
        batch_op.drop_index(batch_op.f('ix_beach_access_access_name'))

    with op.batch_alter_table('advisory_limits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'project_area-nokeys', ['site_id'], ['id'])

    op.create_table('project_area-nokeys',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('row_entry_date', sa.VARCHAR(length=32), nullable=True),
    sa.Column('row_update_date', sa.VARCHAR(length=32), nullable=True),
    sa.Column('area_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('display_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('bounding_box', sa.TEXT(), nullable=True),
    sa.Column('site_type_id', sa.INTEGER(), nullable=True)
    )
    op.create_table('sample__site-nokeys',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('site_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('epa_id', sa.VARCHAR(length=32), nullable=True),
    sa.Column('county', sa.VARCHAR(length=32), nullable=True),
    sa.Column('row_entry_date', sa.VARCHAR(length=32), nullable=True),
    sa.Column('row_update_date', sa.VARCHAR(length=32), nullable=True),
    sa.Column('project_site_id', sa.INTEGER(), nullable=True),
    sa.Column('advisory_text', sa.VARCHAR(length=32), nullable=True),
    sa.Column('issues_advisories', sa.BOOLEAN(), nullable=True),
    sa.Column('has_current_advisory', sa.BOOLEAN(), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('temporary_site', sa.BOOLEAN(), nullable=True),
    sa.Column('site_type_id', sa.INTEGER(), nullable=True),
    sa.Column('city', sa.VARCHAR(length=16), nullable=True),
    sa.Column('post_code', sa.VARCHAR(length=12), nullable=True),
    sa.Column('state_abbreviation', sa.VARCHAR(length=2), nullable=True)
    )
    op.create_table('project_area-oldprod',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('row_entry_date', sa.VARCHAR(length=32), nullable=True),
    sa.Column('row_update_date', sa.VARCHAR(length=32), nullable=True),
    sa.Column('area_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('display_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('bounding_box', sa.TEXT(), nullable=True),
    sa.Column('site_type_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['site_type_id'], ['project_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_type-nokeys',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('row_entry_date', sa.VARCHAR(length=32), nullable=True),
    sa.Column('row_update_date', sa.VARCHAR(length=32), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True)
    )
    op.create_table('site_type-oldprod',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('row_entry_date', sa.VARCHAR(length=32), nullable=True),
    sa.Column('row_update_date', sa.VARCHAR(length=32), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_timeouts-nokeys',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('row_entry_date', sa.VARCHAR(length=32), nullable=True),
    sa.Column('row_update_date', sa.VARCHAR(length=32), nullable=True),
    sa.Column('name', sa.VARCHAR(length=32), nullable=True),
    sa.Column('hours_valid', sa.INTEGER(), nullable=True),
    sa.Column('site_type_id', sa.INTEGER(), nullable=True),
    sa.Column('project_site_id', sa.INTEGER(), nullable=True)
    )
    op.create_table('shell_cast-nokeys',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('row_entry_date', sa.VARCHAR(length=32), nullable=True),
    sa.Column('row_update_date', sa.VARCHAR(length=32), nullable=True),
    sa.Column('site_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('site_url', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('sample_site_id', sa.INTEGER(), nullable=True),
    sa.Column('wkt_extent', sa.TEXT(), nullable=True)
    )
    op.create_table('advisory_limits-nokeys',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('row_entry_date', sa.VARCHAR(length=32), nullable=True),
    sa.Column('row_update_date', sa.VARCHAR(length=32), nullable=True),
    sa.Column('site_id', sa.INTEGER(), nullable=True),
    sa.Column('min_limit', sa.FLOAT(), nullable=True),
    sa.Column('max_limit', sa.FLOAT(), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=32), nullable=True),
    sa.Column('limit_type', sa.VARCHAR(length=32), nullable=True)
    )
    op.create_table('beach_access-nokeys',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('row_entry_date', sa.VARCHAR(length=32), nullable=True),
    sa.Column('row_update_date', sa.VARCHAR(length=32), nullable=True),
    sa.Column('county', sa.VARCHAR(length=32), nullable=True),
    sa.Column('parking_spaces', sa.INTEGER(), nullable=True),
    sa.Column('parking_type', sa.VARCHAR(length=32), nullable=True),
    sa.Column('parking_fee', sa.VARCHAR(length=32), nullable=True),
    sa.Column('ada_parking', sa.VARCHAR(length=8), nullable=True),
    sa.Column('ada_accessible', sa.VARCHAR(length=8), nullable=True),
    sa.Column('rv_parking', sa.VARCHAR(length=8), nullable=True),
    sa.Column('rv_spaces', sa.VARCHAR(length=8), nullable=True),
    sa.Column('restrooms', sa.VARCHAR(length=8), nullable=True),
    sa.Column('trash_cans', sa.VARCHAR(length=8), nullable=True),
    sa.Column('recycling', sa.VARCHAR(length=8), nullable=True),
    sa.Column('public_transportation', sa.VARCHAR(length=8), nullable=True),
    sa.Column('type_of_access_path', sa.VARCHAR(length=32), nullable=True),
    sa.Column('pet_regulations', sa.VARCHAR(length=32), nullable=True),
    sa.Column('lifeguard', sa.VARCHAR(length=8), nullable=True),
    sa.Column('access_sign', sa.VARCHAR(length=8), nullable=True),
    sa.Column('consessions', sa.VARCHAR(length=8), nullable=True),
    sa.Column('adopt_a_beach', sa.VARCHAR(length=8), nullable=True),
    sa.Column('parking', sa.VARCHAR(length=8), nullable=True),
    sa.Column('beach_name', sa.VARCHAR(length=32), nullable=True),
    sa.Column('access_name', sa.VARCHAR(length=32), nullable=True),
    sa.Column('location_address', sa.VARCHAR(length=64), nullable=True),
    sa.Column('area', sa.VARCHAR(length=32), nullable=True),
    sa.Column('adminstrative_body', sa.VARCHAR(length=32), nullable=True),
    sa.Column('general_url', sa.VARCHAR(), nullable=True),
    sa.Column('regulations_url', sa.VARCHAR(), nullable=True),
    sa.Column('web_cam_url', sa.VARCHAR(), nullable=True),
    sa.Column('region', sa.VARCHAR(length=32), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('showers', sa.VARCHAR(length=8), nullable=True),
    sa.Column('sample_site_id', sa.INTEGER(), nullable=True)
    )
    with op.batch_alter_table('general_program_popup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_general_program_popup_sample_site_id'))

    op.drop_table('general_program_popup')
    # ### end Alembic commands ###
