"""empty message

Revision ID: e76ab880d73c
Revises: ce39615f54c6
Create Date: 2024-03-29 15:31:21.348193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e76ab880d73c'
down_revision = 'ce39615f54c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beach_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_beach_access_access_name'), ['access_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_beach_access_sample_site_id'), ['sample_site_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beach_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_beach_access_sample_site_id'))
        batch_op.drop_index(batch_op.f('ix_beach_access_access_name'))

    # ### end Alembic commands ###
