"""empty message

Revision ID: e7d52be7ab80
Revises: b7e6bdcebcd8
Create Date: 2024-03-29 10:42:34.630246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7d52be7ab80'
down_revision = 'b7e6bdcebcd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beach_access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('showers', sa.String(length=8), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beach_access', schema=None) as batch_op:
        batch_op.drop_column('showers')

    # ### end Alembic commands ###
