"""empty message

Revision ID: eeb7ed46c96c
Revises: 5a048aa260a7
Create Date: 2022-02-24 08:02:43.150251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeb7ed46c96c'
down_revision = '5a048aa260a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_program_info', schema=None) as batch_op:
        batch_op.drop_constraint('fk_collection_program_type', type_='foreignkey')
        batch_op.drop_column('collection_program_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_program_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collection_program_type', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_collection_program_type', 'collection_program_type', ['collection_program_type'], ['id'])

    # ### end Alembic commands ###
