"""empty message

Revision ID: f01da78973c0
Revises: 09580d9f6d3e
Create Date: 2022-11-01 17:23:21.144174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f01da78973c0'
down_revision = '09580d9f6d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webCOOS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_entry_date', sa.String(length=32), nullable=True),
    sa.Column('row_update_date', sa.String(length=32), nullable=True),
    sa.Column('webcoos_id', sa.String(length=64), nullable=True),
    sa.Column('sample_site_id', sa.Integer(), nullable=True),
    sa.Column('site_url', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['sample_site_id'], ['sample__site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webCOOS')
    # ### end Alembic commands ###
