"""empty message

Revision ID: f7e51f073865
Revises: 3bb7beb9c06c
Create Date: 2022-02-22 12:24:16.010377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7e51f073865'
down_revision = '3bb7beb9c06c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_info_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_abbreviation', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_info_page', schema=None) as batch_op:
        batch_op.drop_column('state_abbreviation')

    # ### end Alembic commands ###
