swagger: "2.0"
info:
  description: This API allows users to get various data, such as current NOWCast predictions as well as current and historical bacterial sample data for sites.
  version: 1.0.0
  title: Hows The Beach API
  # put the contact info for your development or API team
  contact:
    email: ramaged@mailbox.sc.edu

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: users
  description: Operations available to regular users

paths:
  /nowcastsites:
    get:
      tags:
      - users
      summary: Return a FeatureCollection of sites metadata. Call this endpoint first to get a list of the stations and sites available. Can use a bounding box to limit the search to a specific area.
      operationId: nowcastsites
      description: |
        Return a FeatureCollection of sites metadata.
      produces:
      - application/json
      parameters:
      - in: path
        name: bbox
        type: string
        required: false
        description: The bounding box to limit the query to. The format is upper longitude, upper latitude, lower longitude, lower latitude
        example: bbox=-81.1,32.8,-77.8,34


      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/SitesMetaData'
        400:
          description: bad input parameter

  /{project_area}/sites:
    get:
      tags:
      - users
      summary: Return all stations for the given location_name.
      operationId: sites
      description: |
        If no site parameter is given, this returns all the sites for Myrtle Beach.
      produces:
      - application/json
      parameters:
      - in: path
        name: location_name
        type: string
        required: true
        description: This is the geographic site the station is in. Acceptable values are myrtlebeach, follybeach, killdevilhills, or sarasota.

      - in: query
        name: site
        description: pass an optional site id string for looking up specific site.
        required: false
        type: string
      - in: query
        name: wq_limits
        description: pass in True to receive the limits for the water quality tests.
        required: false
        type: string
      - in: query
        name: project_area
        description: pass in True to receive information, such as the display name, for the project area. This is the project_area field from the /nowcastsites above.
        required: false
        type: string
      - in: query
        name: site_type
        description: To receive only one type of site, set this parameter. Currently site types can be Water Quality, Camera Site, Shellfish, Water Quality Nowcast. This is the site_type in the /nowcastsites request above.
        required: false
        type: string


      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/SiteItem'
        400:
          description: bad input parameter

  /{project_area}/{site_name}/bacteria:
    get:
      tags:
      - users
      summary: Return the water quality sample data for the date range provided.
      operationId: bacteriadata
      description: |
        Return the water quality sample data for the date range provided.
      produces:
      - application/json
      parameters:
      - in: path
        name: project_area
        type: string
        required: true
        description: This is the geographic site the station is in. Acceptable values are myrtlebeach, follybeach, killdevilhills, radioisland, or sarasota. This is the project_area field from the /nowcastsites above.

      - in: path
        name: site_name
        type: string
        required: true
        description: This is the station name to query the water quality sampling data for. This is the site_name field from the /nowcastsites above.
      - in: query
        name: startdate
        description: The date/time for the start of the bacteria data query. Format is YYYY-MM-DD HH:MM:SS.
        required: true
        type: string
      - in: query
        name: enddate
        description: The date/time for the end of the bacteria data query. Format is YYYY-MM-DD HH:MM:SS.
        required: true
        type: string

      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/SiteItem'
        400:
          description: bad input parameter


definitions:
  SiteItem:
    description: A GeoJSON response for one or more sites. The response will vary depending on the type of site defined in the site_type parameter. Each one will be described below. Currently there are site_types of "Water Quality", "Shellfish", and "Camera". The site_type will define what type of data payload is present.
    type: object
    required:
    - type
    - id
    - geometry
    - properties
    properties:
      sites:
        properties:
          type:
            type: string
            example: FeatureCollection
          features:
            type: array
            items:
              type: object
              properties:
                geometry:
                  description: A GeoJSON formated geometry field.
                  type: object
                  properties:
                    type:
                      type: string
                    coordinates:
                      type: array
                      items:
                        example: [longitude,latitude]

                description:
                  type: string
                  example: Ocean Lakes Campground
                site_type:
                  type: string
                  example: Water Quality
                site_name:
                  type: string
                  example: WAC-029
                Water Quality:
                  type: object
                  properties:
                    issues_advisories:
                      type: boolean
                    under_advisory:
                      type: boolean
                    current_advisory_text:
                      type: string
                    advisory:
                      type: object
                      properties:
                        date:
                          type: string
                          format: YYYY-MM-DD HH:MM:SS
                        value:
                          type: number
                        hours_data_valid:
                          type: integer
                    nowcasts:
                      type: object
                      properties:
                        date:
                          type: string
                          format: YYYY-MM-DD HH:MM:SS
                        level:
                          type: string
                        hours_data_valid:
                          type: integer

                Shellfish:
                  type: object
                  properties:
                    date:
                      type: string
                      format: YYYY-MM-DD HH:MM:SS
                    value:
                      type: boolean
                    hours_data_valid:
                      type: integer

  BacteriaDataSiteItem:
    description: A GeoJSON response for the supplied station. This contains the sampled bacteria data for the provided startdate/enddate range.
    type: object
    properties:
      properties:
        type: object
        properties:
          type:
            type: string
            example: Feature
          features:
            type: array
            items:
              type: object
              properties:
                geometry:
                  description: A GeoJSON formated geometry field.
                  type: object
                  properties:
                    type:
                      type: string
                    coordinates:
                      type: array
                      items:
                        example: [longitude,latitude]

                description:
                  type: string
                  example: Ocean Lakes Campground
                site_type:
                  type: string
                  example: Water Quality
                site_name:
                  type: string
                  example: WAC-029
                Water Quality:
                  type: object
                  properties:
                    results:
                      type: array
                      items:
                        type: object
                        properties:
                          date:
                            type: string
                            format: YYYY-MM-DD HH:MM:SS
                          value:
                            type: number
                            example: 10.0

  SitesMetaData:
    description: A GeoJSON response for the Nowcast sites. This contains metadata about the sites.
    type: object
    properties:
      properties:
        type: object
        properties:
          type:
            type: string
            example: Feature
          features:
            type: array
            items:
              type: object
              properties:
                geometry:
                  description: A GeoJSON formated geometry field.
                  type: object
                  properties:
                    type:
                      type: string
                    coordinates:
                      type: array
                      items:
                        example: [longitude,latitude]

                description:
                  type: string
                  example: Ocean Lakes Campground
                site_type:
                  type: string
                  example: Water Quality
                site_name:
                  type: string
                  example: WAC-029
                project_area:
                  type: string
                  example: Myrtle Beach
schemes:
 - https
host: api.howsthebeach.org
basePath: /api/v1/